# Generated by Django 4.2.30 on 2026-09-02 12:07

import composer.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComposeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio', models.FileField(blank=True, null=True, upload_to=composer.models.audio_upload_path)),
                ('image_duration', models.PositiveIntegerField(default=3)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=composer.models.clip_upload_path)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='composer.composejob')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
