# Generated by Django 4.2.30 on 2026-09-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composejob',
            name='aspect_ratio',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='composejob',
            name='fit_mode',
            field=models.CharField(default='pad', max_length=10),
        ),
        migrations.AddField(
            model_name='composejob',
            name='output_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composejob',
            name='output_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
