# Generated by Django 4.2.30 on 2026-09-10 08:01

import composer.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('composer', '0002_composejob_aspect_ratio_composejob_fit_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled project', max_length=200)),
                ('composition', models.JSONField(blank=True, default=dict)),
                ('export_file', models.FileField(blank=True, null=True, upload_to=composer.models.project_export_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
